### ISSUE TITLE
Thanks!.

### ISSUE THREAD

**Issue by matiasdelellis** [TaguchiModels/dlibModels#2]
Hi @TaguchiModels 
Just thank you for the work done. 😄 

I work on a facial recognition application for nextcloud. We tried to use the original nextcloud models with very good results, but of course there are people who had these bias problems, who hopefully improve with your work.

So far I'm testing it with a set of test images and at least I'm not seeing regressions. Therefore I am going to recommend that those who have had problems try it.

See:
* https://github.com/matiasdelellis/facerecognition/pull/750

**Comment by TaguchiModels** [comment]
Hi @matiasdelellis,

Thank you for your kind words and for trying the Taguchi model. 😄
I am very happy to hear that you are seeing promising results so far.
Your recommendation to those who have had issues with the original model is very important to me. Knowing that my efforts might help others is incredibly rewarding.

Thank you!
Taguchi
